"""
Proactive Monitor - The "Consciousness Loop" for Phase 4

This is the thin-slice implementation that:
1. Runs a continuous monitoring loop
2. Polls connected services for changes
3. Detects anomalies and important events
4. Generates proactive notifications

Design Philosophy (from Gemini's feedback):
- Keep cycle time <100ms for responsiveness
- Don't wire up all 15 brain modules at once
- Use existing tested intelligence components
- Start simple, prove the loop works, then expand

This integrates with:
- ProactiveSuggestionEngine (already tested, 22/22 passing)
- SemanticMemory (knowledge graph)
- CrossServiceIntelligence (entity resolution)
"""

import asyncio
import copy
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set
import time

logger = logging.getLogger(__name__)


class MonitorState(Enum):
    """Current state of the monitor."""
    STOPPED = "stopped"
    STARTING = "starting"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPING = "stopping"


class AlertPriority(Enum):
    """Priority levels for proactive alerts."""
    LOW = 1       # FYI, can wait
    MEDIUM = 2    # Worth knowing soon
    HIGH = 3      # Needs attention
    URGENT = 4    # Act now


class AlertType(Enum):
    """Types of proactive alerts."""
    # Email
    IMPORTANT_EMAIL = "important_email"
    URGENT_REPLY_NEEDED = "urgent_reply_needed"
    EMAIL_FROM_VIP = "email_from_vip"
    
    # Calendar
    MEETING_SOON = "meeting_soon"
    MEETING_CONFLICT = "meeting_conflict"
    PREP_TIME_NEEDED = "prep_time_needed"
    DEADLINE_APPROACHING = "deadline_approaching"
    
    # Travel
    FLIGHT_DELAYED = "flight_delayed"
    FLIGHT_GATE_CHANGE = "flight_gate_change"
    TRAVEL_DISRUPTION = "travel_disruption"
    
    # Files
    DOCUMENT_SHARED = "document_shared"
    IMPORTANT_FILE_UPDATED = "important_file_updated"
    
    # Tasks
    TASK_OVERDUE = "task_overdue"
    TASK_DUE_SOON = "task_due_soon"
    
    # Patterns
    UNUSUAL_ACTIVITY = "unusual_activity"
    MISSED_ROUTINE = "missed_routine"
    
    # General
    CUSTOM = "custom"


@dataclass
class ProactiveAlert:
    """
    A proactive notification generated by the monitor.
    
    This is what gets delivered to the user before they ask.
    """
    id: str
    type: AlertType
    priority: AlertPriority
    title: str
    message: str
    
    # Context
    source_service: str  # "email", "calendar", "drive", etc.
    entity_id: Optional[str] = None  # ID of relevant item
    related_entities: List[str] = field(default_factory=list)
    
    # Metadata
    created_at: datetime = field(default_factory=datetime.now)
    expires_at: Optional[datetime] = None
    
    # Actions
    suggested_actions: List[Dict[str, Any]] = field(default_factory=list)
    auto_action: Optional[str] = None  # Action to take automatically if approved
    
    # State
    acknowledged: bool = False
    dismissed: bool = False
    acted_on: bool = False
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "type": self.type.value,
            "priority": self.priority.value,
            "title": self.title,
            "message": self.message,
            "source_service": self.source_service,
            "entity_id": self.entity_id,
            "created_at": self.created_at.isoformat(),
            "suggested_actions": self.suggested_actions,
            "acknowledged": self.acknowledged,
            "dismissed": self.dismissed,
        }


@dataclass
class ServiceSnapshot:
    """Snapshot of a service's state at a point in time."""
    service: str
    timestamp: datetime
    data: Dict[str, Any]
    checksum: str  # For quick change detection


@dataclass  
class AnomalyRule:
    """Rule for detecting anomalies in service data."""
    id: str
    name: str
    service: str
    condition: Callable[[Dict, Dict], bool]  # (current, previous) -> bool
    alert_type: AlertType
    priority: AlertPriority
    message_template: str
    enabled: bool = True


class ProactiveMonitor:
    """
    The proactive monitoring system.
    
    Runs a continuous loop that:
    1. Polls services for changes
    2. Detects anomalies using rules
    3. Generates alerts
    4. Delivers notifications
    
    Target: <100ms cycle time for the core loop.
    Service polling is done asynchronously.
    """
    
    def __init__(
        self,
        cycle_interval_ms: int = 100,
        poll_interval_seconds: int = 60,
    ):
        self._cycle_interval = cycle_interval_ms / 1000.0
        self._poll_interval = poll_interval_seconds
        
        # State
        self._state = MonitorState.STOPPED
        self._last_poll: Dict[str, datetime] = {}
        self._snapshots: Dict[str, ServiceSnapshot] = {}
        
        # Alerts
        self._pending_alerts: List[ProactiveAlert] = []
        self._alert_history: List[ProactiveAlert] = []
        self._alert_counter = 0
        
        # Rules
        self._rules: List[AnomalyRule] = []
        self._setup_default_rules()
        
        # Service adapters (will be connected)
        self._service_adapters: Dict[str, Any] = {}
        
        # Event handlers
        self._on_alert: List[Callable[[ProactiveAlert], None]] = []
        self._on_cycle: List[Callable[[float], None]] = []  # cycle_time_ms
        
        # VIP list (important contacts)
        self._vip_contacts: Set[str] = set()
        
        # Stats
        self._cycle_count = 0
        self._total_cycle_time_ms = 0.0
        self._alerts_generated = 0
        
        logger.info(f"ProactiveMonitor initialized (cycle: {cycle_interval_ms}ms, poll: {poll_interval_seconds}s)")
    
    def _setup_default_rules(self):
        """Setup default anomaly detection rules."""
        
        # Rule: Important email (marked as important or from VIP)
        self._rules.append(AnomalyRule(
            id="important_email",
            name="Important Email Detection", 
            service="email",
            condition=lambda curr, prev: self._check_important_emails(curr, prev),
            alert_type=AlertType.IMPORTANT_EMAIL,
            priority=AlertPriority.HIGH,
            message_template="Important email from {sender}: {subject}",
        ))
        
        # Rule: Meeting starting soon
        self._rules.append(AnomalyRule(
            id="meeting_soon",
            name="Meeting Starting Soon",
            service="calendar",
            condition=lambda curr, prev: self._check_meeting_soon(curr),
            alert_type=AlertType.MEETING_SOON,
            priority=AlertPriority.MEDIUM,
            message_template="Meeting '{title}' starts in {minutes} minutes",
        ))
        
        # Rule: Deadline approaching
        self._rules.append(AnomalyRule(
            id="deadline_approaching",
            name="Deadline Approaching",
            service="calendar",
            condition=lambda curr, prev: self._check_deadline_approaching(curr),
            alert_type=AlertType.DEADLINE_APPROACHING,
            priority=AlertPriority.HIGH,
            message_template="Deadline for '{title}' is {time_until}",
        ))
        
        # Rule: Task overdue
        self._rules.append(AnomalyRule(
            id="task_overdue",
            name="Task Overdue",
            service="tasks",
            condition=lambda curr, prev: self._check_task_overdue(curr),
            alert_type=AlertType.TASK_OVERDUE,
            priority=AlertPriority.MEDIUM,
            message_template="Task '{title}' is overdue by {overdue_time}",
        ))
    
    # === Rule Condition Functions ===
    
    def _check_important_emails(self, current: Dict, previous: Dict) -> bool:
        """Check for new important emails."""
        if "messages" not in current:
            return False
        
        prev_ids = set(m.get("id") for m in previous.get("messages", []))
        
        for msg in current.get("messages", []):
            if msg.get("id") not in prev_ids:
                # New message - check if important
                if msg.get("is_important") or msg.get("is_starred"):
                    return True
                # Check if from VIP
                sender = msg.get("from", "").lower()
                if any(vip in sender for vip in self._vip_contacts):
                    return True
        
        return False
    
    def _check_meeting_soon(self, current: Dict) -> bool:
        """Check if a meeting is starting soon (within 15 minutes)."""
        if "events" not in current:
            return False
        
        now = datetime.now()
        soon = now + timedelta(minutes=15)
        
        for event in current.get("events", []):
            start = event.get("start")
            if isinstance(start, str):
                try:
                    start = datetime.fromisoformat(start.replace("Z", "+00:00"))
                except:
                    continue
            if start and now < start < soon:
                if not event.get("_notified_soon"):
                    event["_notified_soon"] = True
                    return True
        
        return False
    
    def _check_deadline_approaching(self, current: Dict) -> bool:
        """Check for approaching deadlines (events with 'deadline' in title)."""
        if "events" not in current:
            return False
        
        now = datetime.now()
        deadline_window = now + timedelta(hours=24)
        
        for event in current.get("events", []):
            title = event.get("title", "").lower()
            if "deadline" in title or "due" in title:
                start = event.get("start")
                if isinstance(start, str):
                    try:
                        start = datetime.fromisoformat(start.replace("Z", "+00:00"))
                    except:
                        continue
                if start and now < start < deadline_window:
                    if not event.get("_notified_deadline"):
                        event["_notified_deadline"] = True
                        return True
        
        return False
    
    def _check_task_overdue(self, current: Dict) -> bool:
        """Check for overdue tasks."""
        if "tasks" not in current:
            return False
        
        now = datetime.now()
        
        for task in current.get("tasks", []):
            if task.get("completed"):
                continue
            due = task.get("due_date")
            if isinstance(due, str):
                try:
                    due = datetime.fromisoformat(due.replace("Z", "+00:00"))
                except:
                    continue
            if due and due < now:
                if not task.get("_notified_overdue"):
                    task["_notified_overdue"] = True
                    return True
        
        return False
    
    # === Service Connection ===
    
    def connect_service(self, name: str, adapter: Any):
        """Connect a service adapter for monitoring."""
        self._service_adapters[name] = adapter
        self._last_poll[name] = datetime.min
        logger.info(f"Connected service: {name}")
    
    def disconnect_service(self, name: str):
        """Disconnect a service adapter."""
        if name in self._service_adapters:
            del self._service_adapters[name]
            del self._last_poll[name]
            if name in self._snapshots:
                del self._snapshots[name]
            logger.info(f"Disconnected service: {name}")
    
    def add_vip_contact(self, email: str):
        """Add a contact to the VIP list (alerts for their emails)."""
        self._vip_contacts.add(email.lower())
    
    def remove_vip_contact(self, email: str):
        """Remove a contact from the VIP list."""
        self._vip_contacts.discard(email.lower())
    
    # === Alert Management ===
    
    def _generate_alert_id(self) -> str:
        """Generate unique alert ID."""
        self._alert_counter += 1
        return f"alert_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{self._alert_counter}"
    
    def _create_alert(
        self,
        rule: AnomalyRule,
        context: Dict[str, Any],
    ) -> ProactiveAlert:
        """Create an alert from a rule match."""
        # Format message with context
        try:
            message = rule.message_template.format(**context)
        except KeyError:
            message = rule.message_template
        
        alert = ProactiveAlert(
            id=self._generate_alert_id(),
            type=rule.alert_type,
            priority=rule.priority,
            title=rule.name,
            message=message,
            source_service=rule.service,
            entity_id=context.get("id"),
            related_entities=context.get("related_entities", []),
        )
        
        return alert
    
    def get_pending_alerts(self) -> List[ProactiveAlert]:
        """Get all pending (unacknowledged) alerts."""
        return [a for a in self._pending_alerts if not a.acknowledged and not a.dismissed]
    
    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert (mark as seen)."""
        for alert in self._pending_alerts:
            if alert.id == alert_id:
                alert.acknowledged = True
                return True
        return False
    
    def dismiss_alert(self, alert_id: str) -> bool:
        """Dismiss an alert (won't show again)."""
        for alert in self._pending_alerts:
            if alert.id == alert_id:
                alert.dismissed = True
                self._alert_history.append(alert)
                self._pending_alerts.remove(alert)
                return True
        return False
    
    # === Event Handlers ===
    
    def on_alert(self, callback: Callable[[ProactiveAlert], None]):
        """Register callback for new alerts."""
        self._on_alert.append(callback)
    
    def on_cycle(self, callback: Callable[[float], None]):
        """Register callback for each monitoring cycle (receives cycle time in ms)."""
        self._on_cycle.append(callback)
    
    def _emit_alert(self, alert: ProactiveAlert):
        """Emit alert to all handlers."""
        self._pending_alerts.append(alert)
        self._alerts_generated += 1
        
        for handler in self._on_alert:
            try:
                handler(alert)
            except Exception as e:
                logger.error(f"Alert handler error: {e}")
    
    # === Monitoring Loop ===
    
    async def _poll_service(self, name: str) -> Optional[Dict]:
        """Poll a single service for its current state."""
        adapter = self._service_adapters.get(name)
        if not adapter:
            return None
        
        try:
            # Different services have different polling methods
            if hasattr(adapter, "get_recent"):
                data = await adapter.get_recent()
            elif hasattr(adapter, "list"):
                data = await adapter.list()
            elif hasattr(adapter, "poll"):
                data = await adapter.poll()
            else:
                # Generic: try to get state
                data = {"state": "unknown"}
            
            return data if isinstance(data, dict) else {"data": data}
            
        except Exception as e:
            logger.error(f"Error polling {name}: {e}")
            return None
    
    async def _check_rules(self, service: str, current: Dict, previous: Dict):
        """Check all rules for a service."""
        for rule in self._rules:
            if rule.service != service or not rule.enabled:
                continue
            
            try:
                if rule.condition(current, previous):
                    # Rule triggered - create alert
                    context = {
                        "service": service,
                        "current": current,
                        "previous": previous,
                        **current,  # Add all current fields for template
                    }
                    alert = self._create_alert(rule, context)
                    self._emit_alert(alert)
                    logger.info(f"Alert generated: {alert.title}")
                    
            except Exception as e:
                logger.error(f"Error checking rule {rule.id}: {e}")
    
    async def _monitoring_cycle(self):
        """
        Single monitoring cycle.
        
        Target: <100ms
        """
        cycle_start = time.perf_counter()
        
        now = datetime.now()
        
        # Check which services need polling
        services_to_poll = []
        for name in self._service_adapters:
            last = self._last_poll.get(name, datetime.min)
            if (now - last).total_seconds() >= self._poll_interval:
                services_to_poll.append(name)
        
        # Poll services that need it (async)
        if services_to_poll:
            poll_tasks = [self._poll_service(name) for name in services_to_poll]
            results = await asyncio.gather(*poll_tasks, return_exceptions=True)
            
            # Process results
            for name, result in zip(services_to_poll, results):
                if isinstance(result, Exception):
                    logger.error(f"Poll error for {name}: {result}")
                    continue
                
                if result:
                    previous = self._snapshots.get(name, ServiceSnapshot(
                        service=name,
                        timestamp=datetime.min,
                        data={},
                        checksum="",
                    ))
                    
                    # Update snapshot (deep copy to prevent mutation issues)
                    self._snapshots[name] = ServiceSnapshot(
                        service=name,
                        timestamp=now,
                        data=copy.deepcopy(result),
                        checksum=str(hash(str(result))),
                    )
                    
                    # Check rules
                    await self._check_rules(name, result, previous.data)
                    
                    self._last_poll[name] = now
        
        # Calculate cycle time
        cycle_time_ms = (time.perf_counter() - cycle_start) * 1000
        self._total_cycle_time_ms += cycle_time_ms
        self._cycle_count += 1
        
        # Emit cycle event
        for handler in self._on_cycle:
            try:
                handler(cycle_time_ms)
            except Exception as e:
                logger.error(f"Cycle handler error: {e}")
    
    async def _run_loop(self):
        """Main monitoring loop."""
        logger.info("Monitoring loop started")
        self._state = MonitorState.RUNNING
        
        while self._state == MonitorState.RUNNING:
            try:
                await self._monitoring_cycle()
                await asyncio.sleep(self._cycle_interval)
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Monitoring cycle error: {e}")
                await asyncio.sleep(1)  # Back off on error
        
        logger.info("Monitoring loop stopped")
    
    # === Control ===
    
    async def start(self):
        """Start the monitoring loop."""
        if self._state != MonitorState.STOPPED:
            logger.warning(f"Cannot start: state is {self._state}")
            return
        
        self._state = MonitorState.STARTING
        self._loop_task = asyncio.create_task(self._run_loop())
        logger.info("ProactiveMonitor started")
    
    async def stop(self):
        """Stop the monitoring loop."""
        if self._state not in (MonitorState.RUNNING, MonitorState.PAUSED):
            return
        
        self._state = MonitorState.STOPPING
        
        if hasattr(self, "_loop_task"):
            self._loop_task.cancel()
            try:
                await self._loop_task
            except asyncio.CancelledError:
                pass
        
        self._state = MonitorState.STOPPED
        logger.info("ProactiveMonitor stopped")
    
    def pause(self):
        """Pause monitoring (temporary)."""
        if self._state == MonitorState.RUNNING:
            self._state = MonitorState.PAUSED
            logger.info("ProactiveMonitor paused")
    
    def resume(self):
        """Resume monitoring."""
        if self._state == MonitorState.PAUSED:
            self._state = MonitorState.RUNNING
            logger.info("ProactiveMonitor resumed")
    
    # === Stats ===
    
    def get_stats(self) -> Dict:
        """Get monitoring statistics."""
        avg_cycle = (
            self._total_cycle_time_ms / self._cycle_count 
            if self._cycle_count > 0 else 0
        )
        
        return {
            "state": self._state.value,
            "cycle_count": self._cycle_count,
            "average_cycle_ms": round(avg_cycle, 2),
            "alerts_generated": self._alerts_generated,
            "pending_alerts": len(self.get_pending_alerts()),
            "connected_services": list(self._service_adapters.keys()),
            "vip_contacts": len(self._vip_contacts),
            "rules_enabled": sum(1 for r in self._rules if r.enabled),
        }


# === Factory Function ===

def create_proactive_monitor(
    cycle_interval_ms: int = 100,
    poll_interval_seconds: int = 60,
) -> ProactiveMonitor:
    """Create a new ProactiveMonitor instance."""
    return ProactiveMonitor(
        cycle_interval_ms=cycle_interval_ms,
        poll_interval_seconds=poll_interval_seconds,
    )
